### PR TITLE
EnvironmentUtils: fix runtime detection for nodejs-14

### PR DESCRIPTION
**Pull request by Tofee**
Signed-off-by: Christophe Chapuis <chris.chapuis@gmail.com>

### CODE REVIEW

**Comment by Herrie82** [comment]
LGTM, suggest to merge to hardknott, honister and newer

**Comment by Tofee** [comment]
Yes, why not hardknott, that would eliminate a deprecation warning.

**Comment by Herrie82** [comment]
> Yes, why not hardknott, that would eliminate a deprecation warning.

Seems you need more coffee, that's what I'm suggesting as well ;)

**Comment by Herrie82** [comment]
I guess this one needs updating as well?

https://github.com/webOS-ports/mojoservice-frameworks/blob/webOS-ports/webOS-OSE/mojoservice/javascript/controller_app.js#L116

**Comment by Tofee** [comment]
You'right right ! I totally missed it.

**Pull request merged**
